kind: Template
apiVersion: v1
metadata:
  name: launcher-documentation
  annotations:
    openshift.io/display-name: "Launcher - Documentation"
    description: This application contains the https://developers.redhat.com/launch documentation
    tags: instant-app,launchpad, documentation
    iconClass: icon-shadowman
    template.openshift.io/long-description: This application contains the Appdev documentation
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/documentation-url: https://github.com/fabric8-launcher
    template.openshift.io/support-url: https://access.redhat.com
labels:
  template: launcher-documentation

parameters:
- name: IMAGE
  value: fabric8/launcher-documentation
  required: true
- name: IMAGE_TAG
  value: latest
  required: true

- description: CPU request
  displayName: CPU request
  required: true
  name: CPU_REQUEST
  value: "10m"

- description: CPU limit
  displayName: CPU limit
  required: true
  name: CPU_LIMIT
  value: "50m"

- description: Memory request
  displayName: Memory request
  required: true
  name: MEMORY_REQUEST
  value: "8M"

- description: Memory limit
  displayName: Memory limit
  required: true
  name: MEMORY_LIMIT
  value: "32M"

- description: Number of deployment replicas
  displayName: Number of deployment replicas
  required: true
  name: REPLICAS
  value: "1"

objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: launcher-documentation
  spec:
    replicas: "${{REPLICAS}}"
    selector:
      service: launcher-documentation
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          service: launcher-documentation
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: launcher-documentation
          env:
          - name: LAUNCHPAD_TRACKER_SEGMENT_TOKEN
            valueFrom:
              configMapKeyRef:
                name: launcher-documentation
                key: tracker.segment.token
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
        restartPolicy: Always
        dnsPolicy: ClusterFirst
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
- kind: Service
  apiVersion: v1
  metadata:
    labels:
      service: launcher-documentation
    name: launcher-documentation
  spec:
    ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      service: launcher-documentation
    sessionAffinity: None
    type: ClusterIP
